# Generated by Django 6.0.2 on 2026-02-14 07:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(help_text='First day of the billing month, e.g. 2025-01-01')),
                ('reading_date', models.DateField(default=django.utils.timezone.now)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reader_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-billing_month'],
            },
        ),
        migrations.CreateModel(
            name='WaterRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('PRIVATE', 'Private / Residential'), ('COMMERCIAL', 'Commercial / Business'), ('GOVERNMENT', 'Government Institution'), ('BULK', 'Bulk / Reseller')], max_length=20)),
                ('minimum_charge', models.DecimalField(decimal_places=2, help_text='Flat charge for minimum volume', max_digits=10)),
                ('minimum_volume', models.DecimalField(decimal_places=2, default=10, help_text='Cu.m included in minimum charge', max_digits=10)),
                ('rate_per_cubic_m', models.DecimalField(decimal_places=4, help_text='Rate per cu.m ABOVE minimum', max_digits=10)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('sb_resolution', models.CharField(blank=True, help_text='Sangguniang Bayan Resolution No.', max_length=50)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('due_date', models.DateField()),
                ('cutoff_date', models.DateField()),
                ('volume_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_charge', models.DecimalField(decimal_places=2, help_text='Water charge from rate table', max_digits=10)),
                ('senior_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('arrears', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unpaid balance carried from previous bills', max_digits=10)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid in Full'), ('OVERDUE', 'Overdue / With Penalty'), ('WRITTEN_OFF', 'Written Off')], default='UNPAID', max_length=20)),
                ('generated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='billing.meterreading')),
            ],
            options={
                'ordering': ['-billing_month'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Format: MHN-YYYY-NNNN', max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=10)),
                ('address', models.TextField()),
                ('barangay', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('classification', models.CharField(choices=[('PRIVATE', 'Private / Residential'), ('COMMERCIAL', 'Commercial / Business'), ('GOVERNMENT', 'Government Institution'), ('BULK', 'Bulk / Reseller')], default='PRIVATE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONNECTED', 'Disconnected'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('meter_number', models.CharField(max_length=50, unique=True)),
                ('meter_size', models.CharField(default='1/2 inch', max_length=20)),
                ('service_address', models.TextField()),
                ('connection_date', models.DateField()),
                ('disconnection_date', models.DateField(blank=True, null=True)),
                ('monthly_minimum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_senior', models.BooleanField(default=False, help_text='Senior Citizen — 20% discount applies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OtherCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('PENALTY', 'Late Payment Penalty'), ('RECONNECTION', 'Reconnection Fee'), ('MATERIAL', 'Materials Charge'), ('LABOR', 'Labor Charge'), ('METER_REPL', 'Meter Replacement'), ('CUSTOM', 'Custom / Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_date', models.DateField(default=django.utils.timezone.now)),
                ('applied_by', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_charge_items', to='billing.bill')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_charges', to='billing.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='meterreading',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='billing.subscriber'),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_type', models.CharField(choices=[('BILLING', 'Monthly Billing'), ('PAYMENT', 'Payment Received'), ('PENALTY', 'Penalty Charge'), ('ADJUSTMENT', 'Adjustment'), ('RECONNECTION', 'Reconnection Fee'), ('MATERIAL', 'Materials / Labor'), ('DISCOUNT', 'Discount Applied'), ('OTHER', 'Other Charge')], max_length=20)),
                ('description', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('or_number', models.CharField(blank=True, help_text='Official Receipt Number', max_length=50)),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.bill')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='billing.subscriber')),
            ],
            options={
                'ordering': ['entry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisconnectionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField(auto_now_add=True)),
                ('cutoff_date', models.DateField()),
                ('amount_overdue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Penalty rate in percent, e.g. 10.00 = 10%', max_digits=5)),
                ('reconnection_fee', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Notice Pending Delivery'), ('DELIVERED', 'Notice Delivered'), ('DISCONNECTED', 'Service Disconnected'), ('RECONNECTED', 'Service Reconnected'), ('CANCELLED', 'Notice Cancelled')], default='PENDING', max_length=20)),
                ('issued_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('reconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disconnection_notices', to='billing.bill')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disconnection_notices', to='billing.subscriber')),
            ],
            options={
                'ordering': ['-notice_date'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billing.subscriber'),
        ),
        migrations.AlterUniqueTogether(
            name='meterreading',
            unique_together={('subscriber', 'billing_month')},
        ),
    ]
