"""
Django settings for macrohon_water project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-water-billing-dev-key-2026-change-in-production'

# DEBUG=True shows error pages. Set to False when deploying to a server.
DEBUG = True
 
# Add your laptop IP or domain here when going live
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
 
# ────────────────────────────────────────────────────────────────
# INSTALLED APPS — every Django module and our billing app
# ────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',        # styled Bootstrap 4 forms
    'crispy_bootstrap4',   # Bootstrap 4 crispy pack
    'django_filters',      # list filtering/search
    'billing',             # our water billing app
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'macrohon_water.urls'
 
TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],  # project-level templates folder
    'APP_DIRS': True,
    'OPTIONS': { 'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
    ]},
}]
 
# ────────────────────────────────────────────────────────────────
# DATABASE — SQLite for development (simpler setup)
# ────────────────────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
 
# Locale — use Philippine timezone
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'Asia/Manila'
USE_I18N      = True
USE_TZ        = True
 
# Static files (CSS, JS, images served at /static/)
STATIC_URL  = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
 
# Media files (user uploads: subscriber photos, attachments)
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
 
# Crispy Forms — use Bootstrap 4 layout
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK          = 'bootstrap4'
 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
 
# Login / logout redirect
LOGIN_REDIRECT_URL  = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
